### PR TITLE
Adding support for Webhooks

### PR DESCRIPTION
**Pull request by sorenmat**
## Description

Adding a webhook for notifying other services when a change happens in flagr.

Pretty much a copy of #410 which seems to be stale. Simplified it a bit and removed the slack
portion of it, since there seems to be some discussions on how to implement that in a sane way.

After this is merged we can rebase #410 and get the slack notification going

## Motivation and Context

Useful for keeping an audit style log in another system
## How Has This Been Tested?

By running the test suite, and done manual testing locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by marceloboeira** [comment]
I'm going to look into how to test this with integration testing so that we can be more sure it works as expected and continuously get supported throughout time.

**Comment by sorenmat** [comment]
This sovled #30 btw :)

**Comment by sorenmat** [comment]
@marceloboeira did you look at the integration tests, or should I take a crack at it?

**Review by zhouzhuojie — COMMENTED** [review]
lgtm, can you rebase and test if it works with the latest gorm2? thanks!

**Pull request closed without merging**
